language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: qcwT5Erez4oVf1CpKsGm02Xr2v41FNXI0t7fjgGPWgWMiAZOHUIhI/3aEbxV51MiW1LyOQgwNidgWN+d/gseijndNstIxT56uXqfbDC0clL7QvzhHfwOhj6zgrsBDLgRz3lTXK++HP8vPs3o5iyvohOFnymEnwi6/IrxXEAGNzJm2ODIDix3WlGyalist9FqgVeIUyEMCu5T+zai/T+ltm/0PGV+mx8Rsd4Tvvq3vKklwxffb4JWHB/VRzt8TJpObUTTmTwWNc/4ELCpNeM8/yyTDBepCW2MTiua9zJE4aLdQQMKM2krl7lIaq3lXMPSs5J+KZZxb1Z3evn/AHZW19AymG/hTk+iiT9Iu7JKK0VOPLJqsLCdcY4D55CM47a/cyKYEUl7nzWrFjki4xUfuH6A4HkjNrTkxVNFecBk5Z3QTGseT4c0A/skchGKDM33MCq+V8DTjrU5J9QLsv7Q5ZLaQMg3Q1JfpW5HpvkF3Do4q6PzGAqUP5bWCFLBNZPED6fwNZxZOVJSn3G3Cp0Mz2LstI2ZO54Ne2TYI59K7p0eBIt9NEMgUgpgXW1ttUqyVfF/wOM2JNz1BcHQSukIIUGc5VOKsiN1zvE6VGZvbHxeDJt/jL6TQGBYUicY30RRC0wgqkSGRHxgo5npsd9GkCz5pYlmClRVJn82e5lTuvU=
